apiVersion: v1
kind: Service
metadata:
  name: discipline3-service
  namespace: default
spec:
  selector:
    app: discipline3
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
