apiVersion: apps/v1
kind: Deployment
metadata:
  name: discipline2-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discipline2
  template:
    metadata:
      labels:
        app: discipline2
    spec:
      containers:
        - name: discipline2
          image: gcr.io/servicio-440415/discipline2-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key.json"
          volumeMounts:
            - name: pubsub-key
              mountPath: "/secrets"
              readOnly: true
      volumes:
        - name: pubsub-key
          secret:
            secretName: pubsub-key