prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
  additionalServiceMonitors:
    - name: services-monitor
      selector:
        matchLabels:
          monitor: "true"
      endpoints:
        - port: http
    - name: grpc-services-monitor
      selector:
        matchLabels:
          monitor: "true"
      endpoints:
        - port: grpc

  additionalRuleGroups:
    - name: service.rules
      rules:
      - alert: PodNotRunning
        expr: kube_pod_status_phase{phase!="Running"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running
      - alert: ServiceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Service {{ $labels.job }} is down
      - alert: RedisDown
        expr: redis_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Redis instance is down