apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
  - name: service.rules
    rules:
    # Pod health
    - alert: PodNotRunning
      expr: kube_pod_status_phase{phase!="Running"} > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running
    
    # Service health
    - alert: ServiceDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Service {{ $labels.job }} is down
    
    # Redis metrics
    - alert: RedisDown
      expr: redis_up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Redis instance is down