apiVersion: v1
kind: Service
metadata:
  name: ingenieria-service
  namespace: default
spec:
  selector:
    app: ingenieria
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP